services:
  db:
    restart: always
    ports: []

  redis:
    restart: always
    ports: []

  backend:
    image: ghcr.io/danieltinazzi/timeline-backend/timeline-backend:main
    pull_policy: always
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: prod

volumes:
  redis_data:
  postgres_data: