services:
  db:
    restart: always
    ports: []

  redis:
    restart: always

  backend:
    image: ghcr.io/danieltinazzi/timeline-backend:main
    pull_policy: always
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: prod