name: timeline

services:
  db:
    image: postgres:17.6-trixie
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8.2-bookworm
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build: .
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: dev
      POSTGRES_URL: ${POSTGRES_URL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8080:8080"

volumes:
  redis_data:
  postgres_data:
